# CMake generated Testfile for 
# Source directory: /Users/saraalam/Projects/SPECIAL/exp
# Build directory: /Users/saraalam/Projects/SPECIAL/exp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(q1 "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q1")
set_tests_properties(q1 PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;23;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q1_a "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q1_a")
set_tests_properties(q1_a PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;24;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q1_b "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q1_b")
set_tests_properties(q1_b PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;25;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q2 "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q2")
set_tests_properties(q2 PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;28;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q2_a "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q2_a")
set_tests_properties(q2_a PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;29;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q2_b "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q2_b")
set_tests_properties(q2_b PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;30;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q2_eps "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q2_eps")
set_tests_properties(q2_eps PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;31;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q3 "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q3")
set_tests_properties(q3 PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;34;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q3_a "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q3_a")
set_tests_properties(q3_a PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;35;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q3_b "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q3_b")
set_tests_properties(q3_b PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;36;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q4 "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q4")
set_tests_properties(q4 PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;39;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q4_a "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q4_a")
set_tests_properties(q4_a PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;40;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q4_b "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q4_b")
set_tests_properties(q4_b PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;41;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q4_eps "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q4_eps")
set_tests_properties(q4_eps PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;42;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q5 "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q5")
set_tests_properties(q5 PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;45;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q5_b "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q5_b")
set_tests_properties(q5_b PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;46;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q5_a "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q5_a")
set_tests_properties(q5_a PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;47;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q6 "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q6")
set_tests_properties(q6 PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;50;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q6_b "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q6_b")
set_tests_properties(q6_b PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;51;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q7 "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q7")
set_tests_properties(q7 PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;54;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q7_b "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q7_b")
set_tests_properties(q7_b PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;55;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q8 "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q8")
set_tests_properties(q8 PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;58;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q8_b "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q8_b")
set_tests_properties(q8_b PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;59;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q8_eps "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q8_eps")
set_tests_properties(q8_eps PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;60;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q2_scale "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q2_scale")
set_tests_properties(q2_scale PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;63;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q4_scale "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q4_scale")
set_tests_properties(q4_scale PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;64;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(q8_scale "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_q8_scale")
set_tests_properties(q8_scale PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;65;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(selection "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_selection")
set_tests_properties(selection PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;68;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(parallel_join "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_parallel_join")
set_tests_properties(parallel_join PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;69;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
add_test(plan_test "./run" "/Users/saraalam/Projects/SPECIAL/bin/test_plan_test")
set_tests_properties(plan_test PROPERTIES  WORKING_DIRECTORY "/Users/saraalam/Projects/SPECIAL/" _BACKTRACE_TRIPLES "/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;14;add_test;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;70;add_exp_case_with_run;/Users/saraalam/Projects/SPECIAL/exp/CMakeLists.txt;0;")
